"use client";

import { invokeCommand } from "@/lib/tauri";
import { ToolDefinition } from "@/lib/types";
import { useQuery } from "@tanstack/react-query";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import {
  AlertCircle,
  Calculator,
  Camera,
  CheckCircle2,
  ChevronRight,
  Clipboard,
  Clock,
  Cpu,
  FileCode,
  Globe,
  Keyboard,
  MousePointer,
  Play,
  Terminal,
  Wrench,
} from "lucide-react";
import { useState } from "react";

function getToolCategory(name: string): "Browser" | "OS & Automation" | "Terminal & Files" | "System" {
  if (name.startsWith("browser_")) return "Browser";
  if (name.startsWith("mouse_") || name.startsWith("type_") || name.startsWith("press_") || name.includes("screenshot")) {
    return "OS & Automation";
  }
  if (name.includes("file") || name.includes("shell") || name.includes("command") || name.startsWith("clipboard_") || name === "list_directory" || name === "open_app_or_url") {
    return "Terminal & Files";
  }
  return "System";
}

function getToolIcon(name: string) {
  if (name.includes("screenshot")) return Camera;
  if (name.startsWith("mouse_")) return MousePointer;
  if (name.startsWith("type_") || name.startsWith("press_")) return Keyboard;
  if (name.includes("shell") || name.includes("command")) return Terminal;
  if (name.startsWith("browser_")) return Globe;
  if (name.includes("file") || name === "list_directory") return FileCode;
  if (name.startsWith("clipboard_")) return Clipboard;
  if (name === "get_system_metrics") return Cpu;
  if (name === "get_current_time") return Clock;
  if (name === "calculate_expression") return Calculator;
  return Wrench;
}

function getDefaultArgsForTool(name: string): Record<string, unknown> {
  switch (name) {
    case "take_screenshot":
      return {};
    case "mouse_move":
      return { x: 500, y: 300 };
    case "mouse_click":
      return { button: "left", click_type: "single" };
    case "mouse_drag":
      return { start_x: 200, start_y: 200, end_x: 400, end_y: 400 };
    case "mouse_scroll":
      return { delta_y: 5 };
    case "type_text":
      return { text: "Hello from KOKI Agent!" };
    case "press_key":
      return { key: "space" };
    case "execute_shell_command":
      return { command: "uname -a && echo 'KOKI native terminal execution active'" };
    case "browser_navigate":
      return { url: "https://example.com" };
    case "browser_screenshot":
      return { url: "https://example.com", full_page: false };
    case "browser_action":
      return { action: "evaluate", url: "https://example.com", script: "document.title" };
    case "read_file":
      return { path: "package.json", max_lines: 20 };
    case "write_file":
      return { path: "agent_test.txt", content: "Test generated by KOKI assistant" };
    case "append_file":
      return { path: "agent_test.txt", content: "\nAppended line" };
    case "clipboard_read":
      return {};
    case "clipboard_write":
      return { text: "KOKI copied to clipboard!" };
    case "open_app_or_url":
      return { target: "https://github.com" };
    case "calculate_expression":
      return { expression: "128 * 4 + 512" };
    case "list_directory":
      return { path: "." };
    default:
      return {};
  }
}

export function ToolInspector() {
  const [runningTool, setRunningTool] = useState<string | null>(null);
  const [toolResults, setToolResults] = useState<Record<string, unknown>>({});
  const [activeCategory, setActiveCategory] = useState<string>("All");

  const { data: tools, isLoading } = useQuery({
    queryKey: ["rig-tools"],
    queryFn: async () => {
      return await invokeCommand<ToolDefinition[]>("get_available_tools");
    },
  });

  const handleTestTool = async (toolName: string) => {
    setRunningTool(toolName);
    try {
      const args = getDefaultArgsForTool(toolName);
      const result = await invokeCommand<unknown>("run_tool_direct", {
        toolName,
        arguments: args,
      });

      setToolResults((prev) => ({ ...prev, [toolName]: result }));
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      setToolResults((prev) => ({ ...prev, [toolName]: { error: msg } }));
    } finally {
      setRunningTool(null);
    }
  };

  if (isLoading) {
    return (
      <div className="py-16 text-center text-xs text-muted-foreground flex flex-col items-center justify-center gap-2">
        <Wrench className="w-5 h-5 text-primary animate-spin" />
        Loading native tool registry...
      </div>
    );
  }

  const categories = ["All", "Browser", "OS & Automation", "Terminal & Files", "System"];
  const filteredTools = (tools || []).filter((t) => {
    if (activeCategory === "All") return true;
    return getToolCategory(t.name) === activeCategory;
  });

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
          Native & Browser Tool Suite ({tools?.length || 0} registered)
        </span>
        <div className="flex items-center gap-1.5 flex-wrap">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-2.5 py-1 rounded-md text-[11px] font-medium transition-all ${
                activeCategory === cat
                  ? "bg-primary text-primary-foreground shadow-sm"
                  : "bg-secondary text-muted-foreground hover:text-foreground hover:bg-secondary/80"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        {filteredTools.map((tool) => {
          const hasResult = tool.name in toolResults;
          const isExecuting = runningTool === tool.name;
          const Icon = getToolIcon(tool.name);
          const category = getToolCategory(tool.name);
          const result = toolResults[tool.name] as Record<string, unknown> | undefined;
          const isError = result && "error" in result;
          const imageDataUri = (result?.image_data_uri as string) || undefined;

          return (
            <Card key={tool.name} className="p-4 flex flex-col justify-between space-y-3">
              <div className="space-y-2">
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-1.5 min-w-0">
                    <div className="h-6 w-6 rounded bg-primary/10 text-primary flex items-center justify-center shrink-0">
                      <Icon className="h-3.5 w-3.5" />
                    </div>
                    <span className="text-xs font-mono font-bold text-foreground truncate">
                      {tool.name}
                    </span>
                  </div>
                  <Badge variant="secondary" className="text-[10px] font-mono shrink-0">
                    {category}
                  </Badge>
                </div>

                <p className="text-xs text-muted-foreground leading-snug">
                  {tool.description}
                </p>
              </div>

              <div className="space-y-2.5 pt-2 border-t border-border/50">
                {hasResult && (
                  <div className="p-2.5 rounded-lg bg-secondary/80 border border-border text-[11px] font-mono space-y-1.5">
                    <div className="flex items-center justify-between">
                      <div className={`flex items-center gap-1 text-[10px] font-semibold ${isError ? "text-destructive" : "text-success"}`}>
                        {isError ? <AlertCircle className="h-3 w-3" /> : <CheckCircle2 className="h-3 w-3" />}
                        {isError ? "Error" : "Output"}
                      </div>
                    </div>

                    {imageDataUri ? (
                      <div className="border border-border rounded overflow-hidden max-h-32 bg-black/40 flex items-center justify-center">
                        <img src={imageDataUri} alt="Captured preview" className="object-contain max-h-32 w-full" />
                      </div>
                    ) : (
                      <pre className="overflow-x-auto text-foreground custom-scrollbar max-h-32 text-[10px]">
                        {JSON.stringify(toolResults[tool.name], null, 2)}
                      </pre>
                    )}
                  </div>
                )}

                <Button
                  variant="outline"
                  size="sm"
                  className="w-full text-xs gap-1.5 h-8"
                  disabled={isExecuting}
                  onClick={() => handleTestTool(tool.name)}
                >
                  <Play className="h-3 w-3 text-primary" />
                  {isExecuting ? "Executing..." : "Test Run"}
                </Button>
              </div>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
